//! [`Subject`] — the thing being moderated.
//!
//! Per `design.md` §4, a Subject is an account, post, list, or feed — anything
//! a moderation action can target. A Subject is identified by [`SubjectId`]
//! and additionally carries its ATProto identity (`did` for accounts, `uri`
//! for records).
//!
//! `risk_signals` is a denormalized JSONB column maintained by a Postgres
//! trigger (see migration `00000000000007_risk_signals_trigger.sql`). The
//! signal vector is rebuilt whenever an [`crate::observation::Observation`]
//! attached to this subject is inserted or deleted; readers therefore get a
//! consistent snapshot in a single row read.

use chrono::{DateTime, Utc};

use crate::ids::{AtUri, Did, SubjectId};

/// What kind of thing the subject is. Determines which ATProto handle
/// (`did` vs `uri`) is populated.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "lowercase")]
pub enum SubjectKind {
    /// An ATProto account, identified by DID.
    Account,
    /// A post, identified by AT-URI.
    Post,
    /// A user-curated list, identified by AT-URI.
    List,
    /// A feed generator, identified by AT-URI.
    Feed,
}

impl SubjectKind {
    /// Lowercase wire form (`"account"`, `"post"`, ...).
    ///
    /// Used by the repo layer to convert to and from the Postgres `TEXT`
    /// column with a `CHECK (kind IN ('account', ...))` constraint. The
    /// returned strings are stable across schema migrations.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Account => "account",
            Self::Post => "post",
            Self::List => "list",
            Self::Feed => "feed",
        }
    }

    /// Parse a [`SubjectKind`] from its wire form.
    ///
    /// Returns `None` for any string that doesn't match
    /// [`SubjectKind::as_str`]. Callers are responsible for surfacing the
    /// mismatch as a typed error (e.g. `RepoError::Decode`); the bare
    /// `Option` keeps `polaris-types` from depending on `thiserror` or a
    /// repo-specific error type.
    #[must_use]
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "account" => Some(Self::Account),
            "post" => Some(Self::Post),
            "list" => Some(Self::List),
            "feed" => Some(Self::Feed),
            _ => None,
        }
    }
}

impl std::fmt::Display for SubjectKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A computed risk signal attached to a [`Subject`].
///
/// The signal vector is denormalized from the latest N observations on the
/// subject (see migration `00000000000007_risk_signals_trigger.sql`). It is
/// **derived state**, not authoritative — the authoritative observations
/// live in their own table. The denormalized column exists so the
/// case-view UI can render the subject's risk snapshot in a single row read.
///
/// `Signal` is intentionally a small flat record (kind + confidence +
/// timestamp) rather than re-using the full [`crate::observation::Observation`]
/// shape: the trigger that maintains the column compresses each observation
/// to these three fields to keep the JSONB payload bounded.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Signal {
    /// The kind discriminator copied from the source observation.
    pub kind: String,
    /// Detector confidence on the source observation (0.0–1.0).
    pub confidence: f32,
    /// When the source observation was recorded.
    pub detected_at: DateTime<Utc>,
}

/// The thing being moderated.
///
/// Maps 1:1 with the `subjects` table in `00000000000003_subjects_incidents.sql`.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Subject {
    /// Polaris-internal identifier.
    pub id: SubjectId,
    /// What this subject is (account/post/list/feed).
    pub kind: SubjectKind,
    /// ATProto DID — populated when `kind == Account`, may be populated for
    /// records when the subject's authoring DID is known.
    pub did: Option<Did>,
    /// ATProto AT-URI — populated when `kind != Account`.
    pub uri: Option<AtUri>,
    /// Creation time of the subject itself (e.g. account/post creation
    /// upstream). Distinct from `first_seen_by_mod`.
    pub created_at: DateTime<Utc>,
    /// When Polaris first observed this subject in the moderation pipeline.
    pub first_seen_by_mod: DateTime<Utc>,
    /// Denormalized risk signals — see [`Signal`].
    pub risk_signals: Vec<Signal>,
}

/// Caller-supplied fields for inserting a new [`Subject`].
///
/// `id`, `first_seen_by_mod`, and `risk_signals` are populated by the repo
/// (the row's PK is autogenerated server-side; the timestamp defaults to
/// `now()`; the signal vector defaults to `[]` and is filled by the trigger
/// on observation insert).
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NewSubject {
    /// Subject kind discriminator.
    pub kind: SubjectKind,
    /// ATProto DID (see [`Subject::did`]).
    pub did: Option<Did>,
    /// ATProto AT-URI (see [`Subject::uri`]).
    pub uri: Option<AtUri>,
    /// Upstream creation time.
    pub created_at: DateTime<Utc>,
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "test code is allowed to panic — rust-quality §7 convention"
)]
mod tests {
    use super::*;

    #[test]
    fn subject_kind_round_trips_through_wire_form() {
        for k in [
            SubjectKind::Account,
            SubjectKind::Post,
            SubjectKind::List,
            SubjectKind::Feed,
        ] {
            let back = SubjectKind::from_wire(k.as_str()).expect("known wire form");
            assert_eq!(k, back);
        }
    }

    #[test]
    fn subject_kind_rejects_unknown_wire_form() {
        assert!(SubjectKind::from_wire("MOdErAtor").is_none());
        assert!(SubjectKind::from_wire("").is_none());
    }

    #[test]
    fn subject_kind_serializes_lowercase() {
        let json = serde_json::to_string(&SubjectKind::Account).expect("serialize");
        assert_eq!(json, "\"account\"");
    }
}
