//! Labeler signing-key trait + custody implementations (issue #29 / REQ-11).
//!
//! Polaris's K-256 signing key is the labeler's identity: every
//! `com.atproto.label.defs::Label` row emitted on the wire is signed with
//! this key and consumers verify the signature against the public key
//! Polaris publishes in its `app.bsky.labeler.service` record. The key
//! must be guarded as one of the two most sensitive secrets the process
//! holds (the other being the moderator-session cookie key from
//! [`crate::config::SecurityConfig`]).
//!
//! # Four custody postures
//!
//! v1 ships four implementations of [`SigningKey`], selected by
//! `[labeler.signing_key] mode` at startup:
//!
//! | Mode                | At-rest defense | Code-exec defense | Restart UX        |
//! |---------------------|-----------------|-------------------|-------------------|
//! | `file-plain`        | none            | none              | zero-touch        |
//! | `passphrase-sealed` | AES-256-GCM + scrypt | none         | passphrase prompt |
//! | `os-keychain`       | OS keychain     | none              | zero-touch        |
//! | `cloud-kms-oracle`  | KMS at rest     | per-`sign()` RPC  | zero-touch        |
//!
//! `.design/polaris-proto-blue-integration.md` §B (REQ-11) is the
//! authoritative discussion of why each mode exists and what threat
//! model it covers; this module is the implementation.
//!
//! # Boot-time profile enforcement (AC-14)
//!
//! [`build_signing_key`] is a *startup-only* validator. The Bluesky
//! deployment profile explicitly disallows `file-plain` because a
//! first-party deployment running KMS infrastructure should never
//! regress to a plaintext on-disk key. The combination produces a typed
//! [`SigningError::WrongProfile`] error which the binary entrypoint
//! converts into a non-zero exit before any HTTP traffic begins.
//!
//! # Signature shape
//!
//! `sign()` returns a [`Signature`] — a newtype around `[u8; 64]`
//! holding the K-256 ECDSA compact signature as
//! `r (32 bytes, big-endian) || s (32 bytes, big-endian)`. This is the
//! exact layout the atproto label-signing contract expects (see
//! `proto_blue_crypto::K256Keypair::sign`). The S-component is low-S
//! normalised so the signature is not malleable.
//!
//! # No `Arc<Mutex<…>>`
//!
//! Every concrete signer is constructed once at startup and is
//! thereafter immutable. The factory returns `Arc<dyn SigningKey>`
//! purely so heterogeneous backends can share a storage slot; there is
//! no interior mutability and no lock. (A request-time AES-GCM nonce
//! is generated by the [`passphrase_sealed`] *write* path, not by the
//! `sign` path.)

use std::sync::Arc;

use proto_blue::crypto::K256Keypair;

use crate::config::{LabelerSigningKeyConfig, Profile};

pub mod cloud_kms;
pub mod file_plain;
pub mod os_keychain;
pub mod passphrase_sealed;

/// Sender side of the live-server's active-signer slot.
///
/// Wraps `tokio::sync::watch` around the `Arc<dyn SigningKey>` the
/// emitter consumes. Rotation (issue #30) updates the slot atomically
/// by calling `send`: in the single instant between `send` accepting
/// the new value and existing receivers picking it up, NO emitter
/// observes two simultaneous signers — `watch` semantics guarantee
/// each receiver observes either the old or the new `Arc`, never both.
///
/// In real deployments the rotation CLI and the live server are
/// separate processes; the live server detects a rotation by polling
/// `signing_key_history` on a `tokio::time::interval`, reads the new
/// active key back from its custody store, and pushes the freshly-
/// constructed `Arc<dyn SigningKey>` through this sender. The CLI
/// itself does not touch a live-process `ActiveSigner`. See
/// [`crate::labeler::rotation`] for the discovery-mechanism rationale.
///
/// Tests run in-process and DO hold the sender; they call
/// `signer_tx.send(new_signer)` directly to simulate the live-server's
/// poll-detect-reload sequence (this is the AC-15 binding path).
pub type ActiveSigner = tokio::sync::watch::Sender<Arc<dyn SigningKey>>;

/// Receiver side of the live-server's active-signer slot. See
/// [`ActiveSigner`] for the design rationale.
///
/// `ApiState` carries one of these; emitters call `borrow().clone()`
/// at the top of `emit()` to fetch the current `Arc<dyn SigningKey>`.
pub type ActiveSignerReceiver = tokio::sync::watch::Receiver<Arc<dyn SigningKey>>;

/// Newtype wrapper around `K256Keypair` that provides a `Debug` impl
/// which redacts the secret-bearing inner type.
///
/// `proto_blue::crypto::K256Keypair` deliberately does not implement
/// `Debug` (it holds the K-256 secret scalar), but the [`SigningKey`]
/// trait requires `Debug` on every implementor so the factory's
/// `Arc<dyn SigningKey>` return type composes. Wrapping with this
/// newtype lets concrete signers hold a keypair as a field and still
/// derive a redacted `Debug` for the enclosing struct.
pub(crate) struct RedactedKeypair(pub(crate) K256Keypair);

impl std::fmt::Debug for RedactedKeypair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("RedactedKeypair")
            .field(&"<redacted>")
            .finish()
    }
}

/// A 64-byte K-256 ECDSA compact signature.
///
/// Layout, verbatim from the atproto label-signing contract:
///
/// ```text
/// bytes[ 0..32]  =  r component, 32-byte big-endian unsigned integer
/// bytes[32..64]  =  s component, 32-byte big-endian unsigned integer
/// ```
///
/// The S-component is always low-S normalised so the signature is
/// non-malleable (BIP-62 / RFC 6979 §3.2). Equality is by value; the
/// newtype exists so that a public-API caller cannot mistake an
/// arbitrary 64-byte payload for a label signature.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Signature(pub [u8; 64]);

impl Signature {
    /// Wrap raw signature bytes.
    ///
    /// # Errors
    ///
    /// Returns [`SigningError::Sign`] when `bytes.len() != 64`.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, SigningError> {
        let arr: [u8; 64] = bytes.try_into().map_err(|_| SigningError::Sign {
            reason: "signature must be exactly 64 bytes (K-256 compact form)",
        })?;
        Ok(Self(arr))
    }

    /// Borrow the raw 64-byte signature.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 64] {
        &self.0
    }
}

// Manual Debug — the signature itself is not secret (it's published on
// the wire) but a hex of 64 bytes is noise; render a short fingerprint.
impl std::fmt::Debug for Signature {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Signature")
            .field(&format_args!(
                "{}…{} (64 bytes)",
                hex::encode(&self.0[..4]),
                hex::encode(&self.0[60..])
            ))
            .finish()
    }
}

/// The labeler-signing-key contract.
///
/// Implementations live under `polaris-backend/src/labeler/signer/`. The
/// trait is dyn-compatible: the factory function
/// [`build_signing_key`] returns `Arc<dyn SigningKey>` so the four
/// custody backends can share one storage slot on `ApiState`.
///
/// `Debug` is part of the trait so the factory's return type composes —
/// every concrete impl writes a *manual* `Debug` that redacts any
/// secret material (never `#[derive(Debug)]`).
pub trait SigningKey: Send + Sync + std::fmt::Debug {
    /// Sign `payload` with the labeler's K-256 private key.
    ///
    /// Returns a 64-byte compact [`Signature`] suitable for embedding
    /// in `com.atproto.label.defs::Label.sig`. The signature is
    /// deterministic (RFC 6979) for the in-process custody modes; the
    /// `cloud-kms-oracle` mode delegates to AWS KMS whose ECDSA-SHA256
    /// is also deterministic under the same RFC.
    ///
    /// # Errors
    ///
    /// Returns [`SigningError::Sign`] on a primitive-level signing
    /// failure (impl-specific), or [`SigningError::Kms`] for the
    /// `cloud-kms-oracle` mode on KMS transport / authentication
    /// failures.
    fn sign(&self, payload: &[u8]) -> Result<Signature, SigningError>;

    /// The labeler's published public key, in `did:key:z…` multikey form.
    ///
    /// This is the string embedded in the operator's
    /// `app.bsky.labeler.service` record so downstream verifiers can
    /// fetch the public key for signature verification. Computed once
    /// at construction time and cached — `sign()` does *not* touch it.
    fn public_key_did(&self) -> &str;
}

/// Errors raised by the four signing-key custody implementations.
///
/// Each variant names a failure *category* — Display strings deliberately
/// do not embed key material, ciphertext, or passphrase fragments so the
/// error chain is safe to log via `tracing::error!(error = ?e, …)`.
#[derive(Debug, thiserror::Error)]
pub enum SigningError {
    /// Failed to load the key from its custody backend (file read, file
    /// mode check, keychain miss, KMS unauthorised, …).
    #[error("failed to load labeler signing key: {reason}")]
    KeyLoad {
        /// Category-level reason. Never includes key material.
        reason: &'static str,
    },

    /// Failed to decrypt a sealed key (wrong passphrase, ciphertext
    /// tampered with, AES-GCM authentication failure).
    #[error("failed to decrypt sealed labeler signing key")]
    KeyDecrypt,

    /// The signing primitive itself failed. Wraps a static category
    /// reason; the underlying error chain is dropped to ensure no key
    /// material leaks through `Display`.
    #[error("signing operation failed: {reason}")]
    Sign {
        /// Category-level reason. Never includes key material.
        reason: &'static str,
    },

    /// A cloud-KMS RPC failed (transport, auth, throttling).
    #[error("cloud KMS RPC failed: {reason}")]
    Kms {
        /// Category-level reason. Never includes key material.
        reason: &'static str,
    },

    /// Startup-time AC-14 refusal: the deployment profile disallows the
    /// configured custody mode. Today this means "Bluesky profile + `file-plain`"
    /// — see [`build_signing_key`].
    #[error("profile {profile:?} refuses signing-key mode {mode:?}")]
    WrongProfile {
        /// The profile that refused the mode (e.g. `"bluesky"`).
        profile: &'static str,
        /// The mode the profile refused (e.g. `"file-plain"`).
        mode: &'static str,
    },
}

/// Build the configured [`SigningKey`] at process start.
///
/// This is the single entry point the binary calls once at startup. It
/// performs the profile-vs-mode safety check from AC-14 *before* it
/// loads any key material, then dispatches to the per-mode constructor.
///
/// # Errors
///
/// Returns [`SigningError::WrongProfile`] if the deployment profile
/// disallows the configured mode (today: Bluesky profile + `file-plain`).
/// Otherwise returns the per-mode constructor's error verbatim.
pub fn build_signing_key(
    cfg: &LabelerSigningKeyConfig,
    profile: Profile,
) -> Result<Arc<dyn SigningKey>, SigningError> {
    // AC-14 part 2: refuse at startup — before any traffic, before any
    // key material is loaded — when the deployment profile disallows
    // the configured custody mode. Today only one combination is
    // disallowed; the check is structured as a single arm so adding a
    // future "Bluesky also disallows os-keychain" rule does not
    // bifurcate the dispatch path.
    if matches!(profile, Profile::Bluesky)
        && matches!(cfg, LabelerSigningKeyConfig::FilePlain { .. })
    {
        return Err(SigningError::WrongProfile {
            profile: "bluesky",
            mode: "file-plain",
        });
    }

    match cfg {
        LabelerSigningKeyConfig::FilePlain { path } => {
            let signer = file_plain::FilePlainSigner::from_path(path)?;
            Ok(Arc::new(signer))
        }
        LabelerSigningKeyConfig::PassphraseSealed { path } => {
            let signer = passphrase_sealed::PassphraseSealedSigner::from_path(path)?;
            Ok(Arc::new(signer))
        }
        LabelerSigningKeyConfig::OsKeychain { account } => {
            let signer = os_keychain::OsKeychainSigner::from_account(account)?;
            Ok(Arc::new(signer))
        }
        LabelerSigningKeyConfig::CloudKms {
            provider,
            key_id,
            region,
        } => {
            let signer = cloud_kms::build_cloud_kms_signer(*provider, key_id, region)?;
            Ok(signer)
        }
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "test code is allowed to panic — rust-quality §7 convention"
)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::config::{KmsProvider, LabelerSigningKeyConfig, Profile};

    // ── AC-14 part 2: refusal ────────────────────────────────────────

    #[test]
    fn bluesky_profile_refuses_file_plain_mode() {
        let cfg = LabelerSigningKeyConfig::FilePlain {
            path: PathBuf::from("/dev/null"),
        };
        let err = build_signing_key(&cfg, Profile::Bluesky)
            .expect_err("Bluesky + file-plain must refuse at startup");
        match err {
            SigningError::WrongProfile { profile, mode } => {
                assert_eq!(profile, "bluesky");
                assert_eq!(mode, "file-plain");
            }
            other => panic!("expected WrongProfile, got {other:?}"),
        }
    }

    #[test]
    fn bluesky_profile_allows_cloud_kms_mode_by_factory_check() {
        // The cloud-KMS constructor itself is feature-gated; the
        // profile check is the only thing the factory does before the
        // per-mode constructor runs, and we want to assert that the
        // profile check does not reject Bluesky + cloud-kms. We
        // construct the config and rely on the *constructor* error
        // (not WrongProfile) to confirm we got past the profile check.
        let cfg = LabelerSigningKeyConfig::CloudKms {
            provider: KmsProvider::Aws,
            key_id: "arn:aws:kms:us-east-1:000000000000:key/00000000-0000-0000-0000-000000000000"
                .to_owned(),
            region: "us-east-1".to_owned(),
        };
        let result = build_signing_key(&cfg, Profile::Bluesky);
        // Whatever happens, it must NOT be WrongProfile — the profile
        // check passed, the constructor decides next. Both `Ok(_)`
        // (feature on, reachable KMS) and `Err(non-WrongProfile)`
        // (no feature / unreachable KMS / etc.) satisfy the contract.
        if let Err(SigningError::WrongProfile { .. }) = result {
            panic!("Bluesky + cloud-kms must pass the profile check");
        }
    }

    #[test]
    fn labeler_profile_permits_file_plain_mode() {
        // The labeler profile defaults to file-plain (matches Ozone's
        // OZONE_SIGNING_KEY_HEX posture). The factory must *not* reject
        // this combination — the WARN log is the only feedback.
        let cfg = LabelerSigningKeyConfig::FilePlain {
            path: PathBuf::from("/this/path/does/not/exist"),
        };
        let err = build_signing_key(&cfg, Profile::Labeler)
            .expect_err("non-existent path must fail at key load, not at profile check");
        assert!(
            !matches!(err, SigningError::WrongProfile { .. }),
            "labeler profile must permit file-plain at the profile-check layer; got {err:?}",
        );
    }

    // ── Signature newtype invariants ─────────────────────────────────

    #[test]
    fn signature_from_bytes_rejects_wrong_length() {
        assert!(Signature::from_bytes(&[0_u8; 63]).is_err());
        assert!(Signature::from_bytes(&[0_u8; 65]).is_err());
        assert!(Signature::from_bytes(&[0_u8; 64]).is_ok());
    }

    #[test]
    fn signature_debug_does_not_dump_all_bytes() {
        // Defensive: the wire signature is not secret, but a 64-byte
        // hex dump in every log line is noise. Confirm the Debug
        // representation is fingerprint-shaped (a few bytes plus an
        // ellipsis), not a full hex blob.
        let sig = Signature([0xAB; 64]);
        let rendered = format!("{sig:?}");
        assert!(rendered.contains('…'), "expected ellipsis: {rendered}");
        assert!(
            !rendered.contains(&"ab".repeat(64)),
            "expected fingerprint, got full hex: {rendered}",
        );
    }
}
