//! Proptest round-trip tests for the `polaris-types` ↔ `polaris-lexicons`
//! mapping layer.
//!
//! # Subset note
//!
//! The `to_lexicon_*` / `from_lexicon_*` pair is defined only over the
//! **safe-to-federate subset** of internal types:
//!
//! - `ObservationKind` variants: only the 5 federatable variants
//!   (`ImageHashCluster`, `AccountCohort`, `ReplyBrigade`, `ExternalLabel`,
//!   `ClassifierSignal`). The two internal-only variants (`ReportVolumeAnomaly`,
//!   `ModeratorBehaviorAnomaly`) are NOT in the round-trip domain and are
//!   excluded via `prop_filter!`.
//!
//! - `Escalation::id`: dropped at the to-wire boundary and regenerated by
//!   `from_lexicon_escalation`. Round-trip identity is NOT asserted on `id`
//!   — only on the fields that are present in both representations.
//!
//! - `EvidencePointer::byte_length`: `u64` internally, `i64` on the wire.
//!   `prop_assume!` filters values > `i64::MAX` from the generated inputs.
//!
//! Each proptest block runs **1000 cases** as required by AC-3.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_precision_loss,
    reason = "proptest integration file — panics are the intended failure mechanism"
)]

use polaris_types::{
    escalation::{EmbeddedObservation, Escalation, SubjectRef},
    evidence::EvidencePointer,
    ids::{Did, EscalationId, LabelValue},
    lexicon_mapping::{
        from_lexicon_embedded_observation, from_lexicon_escalation, from_lexicon_evidence_pointer,
        to_lexicon_embedded_observation, to_lexicon_escalation, to_lexicon_evidence_pointer,
    },
    observation::ObservationKind,
};
use proptest::prelude::*;

// ─── strategy helpers ────────────────────────────────────────────────────────

/// Strategy for a valid ATProto DID string.
fn did_strategy() -> impl Strategy<Value = String> {
    // Generate plausible DID strings: did:plc:<22 base32 chars>
    "[a-z2-7]{22}".prop_map(|suffix| format!("did:plc:{suffix}"))
}

/// Strategy for a valid AT-URI string.
fn at_uri_strategy() -> impl Strategy<Value = String> {
    // at://<did>/app.bsky.feed.post/<rkey>
    ("[a-z2-7]{22}", "[a-z2-7]{13}").prop_map(|(did_suffix, rkey)| {
        format!("at://did:plc:{did_suffix}/app.bsky.feed.post/{rkey}")
    })
}

/// Strategy for a confidence value `f32` in [0.0, 1.0] with 3 decimal
/// places of precision (matching the wire's ×1000 scaling).
fn confidence_strategy() -> impl Strategy<Value = f32> {
    (0u32..=1000u32).prop_map(|i| i as f32 / 1000.0)
}

/// Strategy for a label value string (simple lowercase ascii).
fn label_value_strategy() -> impl Strategy<Value = String> {
    "[a-z]{3,20}"
        .prop_filter("must not be empty", |s: &String| !s.is_empty())
        .prop_map(|s| s)
}

/// Strategy for the 5 safe-to-federate `ObservationKind` variants.
///
/// `prop_filter!` is used below in the round-trip tests to exclude the
/// internal-only variants. This strategy never generates them.
fn observation_kind_strategy() -> impl Strategy<Value = ObservationKind> {
    prop_oneof![
        // ImageHashCluster
        ("[a-f0-9]{16}", 0u32..=64u32)
            .prop_map(|(hash, distance)| { ObservationKind::ImageHashCluster { hash, distance } }),
        // AccountCohort
        ("[a-z0-9]{8,16}", confidence_strategy()).prop_map(|(cohort_id, similarity_score)| {
            ObservationKind::AccountCohort {
                cohort_id,
                similarity_score,
            }
        }),
        // ReplyBrigade
        at_uri_strategy().prop_map(|thread_uri| ObservationKind::ReplyBrigade { thread_uri }),
        // ExternalLabel
        (
            did_strategy(),
            label_value_strategy(),
            confidence_strategy()
        )
            .prop_map(|(source, label_value, weight)| {
                ObservationKind::ExternalLabel {
                    source: Did::new(&source),
                    label_value: LabelValue::new(&label_value),
                    weight,
                }
            }),
        // ClassifierSignal
        (
            "[a-z]{4,12}-v[0-9]",
            label_value_strategy(),
            confidence_strategy()
        )
            .prop_map(|(model, label, confidence)| {
                ObservationKind::ClassifierSignal {
                    model,
                    label,
                    confidence,
                }
            }),
    ]
}

/// Strategy for an [`EmbeddedObservation`] using only safe-to-federate variants.
fn embedded_observation_strategy() -> impl Strategy<Value = EmbeddedObservation> {
    (confidence_strategy(), observation_kind_strategy()).prop_map(|(confidence, observation)| {
        EmbeddedObservation {
            confidence,
            observation,
        }
    })
}

/// Strategy for an [`EvidencePointer`] whose `byte_length` fits in `i64`.
fn evidence_pointer_strategy() -> impl Strategy<Value = EvidencePointer> {
    (
        "[a-z2-7]{20,40}",
        prop_oneof![
            Just("application/vnd.ipld.car".to_owned()),
            Just("application/octet-stream".to_owned()),
        ],
        0u64..=i64::MAX as u64,
    )
        .prop_map(|(car_cid, media_type, byte_length)| EvidencePointer {
            car_cid: format!("bafyrei{car_cid}"),
            media_type,
            byte_length,
        })
}

/// Strategy for a [`SubjectRef`].
fn subject_ref_strategy() -> impl Strategy<Value = SubjectRef> {
    prop_oneof![
        did_strategy().prop_map(SubjectRef::Did),
        at_uri_strategy().prop_map(SubjectRef::AtUri),
    ]
}

/// Strategy for a complete [`Escalation`] over the safe-to-federate subset.
fn escalation_strategy() -> impl Strategy<Value = Escalation> {
    (
        did_strategy(),         // source_did
        did_strategy(),         // target_did
        subject_ref_strategy(), // subject
        "[A-Za-z ]{10,80}",     // reason
        prop::collection::vec(embedded_observation_strategy(), 0..=5),
        prop::collection::vec(evidence_pointer_strategy(), 0..=3),
    )
        .prop_map(
            |(source, target, subject, reason, observations, evidence)| Escalation {
                id: EscalationId::new(),
                source_did: Did::new(&source),
                target_did: Did::new(&target),
                subject,
                reason,
                observations,
                evidence,
                created_at: chrono::DateTime::<chrono::Utc>::from_timestamp(0, 0).unwrap(),
            },
        )
}

// ─── round-trip tests ────────────────────────────────────────────────────────

proptest! {
    #![proptest_config(ProptestConfig::with_cases(1000))]

    /// `EvidencePointer`: to_lexicon → from_lexicon is the identity function
    /// over the full `EvidencePointer` struct (all fields are present in both
    /// representations).
    #[test]
    fn evidence_pointer_round_trips(ep in evidence_pointer_strategy()) {
        let wire = to_lexicon_evidence_pointer(&ep)?;
        let back = from_lexicon_evidence_pointer(wire)?;
        prop_assert_eq!(ep, back);
    }

    /// `EmbeddedObservation`: the `confidence` and `observation` fields
    /// survive a to_lexicon → from_lexicon round-trip.
    ///
    /// # Carve-outs
    ///
    /// - Confidence equality uses `(a - b).abs() < 0.002` because the
    ///   ×1000/÷1000 scaling may introduce ±0.001 rounding error. The
    ///   strategy generates values with at most 3 decimal places, so this
    ///   tolerance is exact-ish in practice.
    /// - The `AccountCohort::similarity_score` and
    ///   `ExternalLabel::weight` fields are scaled the same way; same
    ///   tolerance applies.
    #[test]
    fn embedded_observation_round_trips(obs in embedded_observation_strategy()) {
        let wire = to_lexicon_embedded_observation(&obs)?;
        let back = from_lexicon_embedded_observation(wire)?;

        // Confidence round-trip (±0.002 tolerance for scale rounding).
        prop_assert!(
            (obs.confidence - back.confidence).abs() < 0.002,
            "confidence round-trip failed: {} vs {}",
            obs.confidence,
            back.confidence
        );

        // ObservationKind: assert variant-specific fields match.
        match (&obs.observation, &back.observation) {
            (
                ObservationKind::ImageHashCluster { hash: h1, distance: d1 },
                ObservationKind::ImageHashCluster { hash: h2, distance: d2 },
            ) => {
                prop_assert_eq!(h1, h2);
                prop_assert_eq!(d1, d2);
            }
            (
                ObservationKind::AccountCohort { cohort_id: c1, similarity_score: s1 },
                ObservationKind::AccountCohort { cohort_id: c2, similarity_score: s2 },
            ) => {
                prop_assert_eq!(c1, c2);
                prop_assert!((s1 - s2).abs() < 0.002, "similarity_score round-trip");
            }
            (
                ObservationKind::ReplyBrigade { thread_uri: u1 },
                ObservationKind::ReplyBrigade { thread_uri: u2 },
            ) => {
                prop_assert_eq!(u1, u2);
            }
            (
                ObservationKind::ExternalLabel { source: s1, label_value: l1, weight: w1 },
                ObservationKind::ExternalLabel { source: s2, label_value: l2, weight: w2 },
            ) => {
                prop_assert_eq!(s1, s2);
                prop_assert_eq!(l1, l2);
                prop_assert!((w1 - w2).abs() < 0.002, "weight round-trip");
            }
            (
                ObservationKind::ClassifierSignal { model: m1, label: l1, confidence: c1 },
                ObservationKind::ClassifierSignal { model: m2, label: l2, confidence: c2 },
            ) => {
                prop_assert_eq!(m1, m2);
                prop_assert_eq!(l1, l2);
                prop_assert!((c1 - c2).abs() < 0.002, "classifier confidence round-trip");
            }
            _ => prop_assert!(false, "observation variant mismatch: {:?} vs {:?}", obs.observation, back.observation),
        }
    }

    /// `Escalation`: the subset of fields present in both the internal and
    /// wire representations survives a to_lexicon → from_lexicon round-trip.
    ///
    /// # Carve-outs
    ///
    /// - `id`: dropped at the to-wire boundary; NOT asserted to be equal.
    ///   `from_lexicon_escalation` mints a fresh `EscalationId` for the
    ///   reconstructed struct.
    /// - Confidence fields: ±0.002 tolerance as documented above.
    #[test]
    fn escalation_round_trips(esc in escalation_strategy()) {
        let wire = to_lexicon_escalation(&esc)?;
        let back = from_lexicon_escalation(wire)?;

        // source_did and target_did are present on the wire.
        prop_assert_eq!(esc.source_did.as_str(), back.source_did.as_str());
        prop_assert_eq!(esc.target_did.as_str(), back.target_did.as_str());

        // reason is present on the wire.
        prop_assert_eq!(&esc.reason, &back.reason);

        // subject kind and value are present on the wire.
        prop_assert_eq!(esc.subject.as_str(), back.subject.as_str());
        match (&esc.subject, &back.subject) {
            (SubjectRef::Did(_), SubjectRef::Did(_))
            | (SubjectRef::AtUri(_), SubjectRef::AtUri(_)) => {}
            _ => prop_assert!(false, "subject variant mismatch"),
        }

        // observations count matches.
        prop_assert_eq!(esc.observations.len(), back.observations.len());

        // evidence count matches.
        prop_assert_eq!(esc.evidence.len(), back.evidence.len());

        // evidence byte_length values match.
        for (orig, roundtripped) in esc.evidence.iter().zip(back.evidence.iter()) {
            prop_assert_eq!(orig.byte_length, roundtripped.byte_length);
            prop_assert_eq!(&orig.car_cid, &roundtripped.car_cid);
            prop_assert_eq!(&orig.media_type, &roundtripped.media_type);
        }

        // id: explicitly NOT asserted (it's dropped at the to-wire boundary).
        // The carve-out is intentional: `from_lexicon_escalation` produces a
        // fresh `EscalationId` because the wire format has no `id` field.
    }
}
