//! Hardware-key (WebAuthn / FIDO2) registration + assertion (#40, design.md §6 + §9.1).
//!
//! Implements the post-login gate that defends against the
//! compromised-moderator-account threat (design.md §9.1). After OIDC or
//! ATProto OAuth completes, [`apply_hardware_key_gate`] (in
//! [`crate::auth::login_gate`]) inspects the resolved [`crate::auth::LoginResult`]
//! and the [`crate::config::AuthConfig::require_hardware_key`] flag to decide
//! whether to mint the session cookie immediately, force the moderator into a
//! hardware-key enrolment ceremony, or require a hardware-key assertion before
//! issuing the cookie.
//!
//! # Crypto + state-handling discipline
//!
//! - **Challenge bytes come from `OsRng`.** The `webauthn-rs` framework
//!   internally draws challenge bytes from the OS CSPRNG; Polaris never
//!   constructs them by hand.
//! - **State never lands in a cookie.** Both [`PasskeyRegistration`] and
//!   [`PasskeyAuthentication`] are bincode-persisted to
//!   `webauthn_register_states` / `webauthn_assert_states`. The cookie surface
//!   carries only an opaque `state` token; the framework's CSRF / replay
//!   invariants live in the persisted blob, not in the client.
//! - **`sign_count` is strictly monotonic.** A presented counter ≤ the stored
//!   counter is a cloning red-flag — we surface
//!   [`WebauthnError::CloningDetected`] and emit `tracing::error!` so the
//!   security operator's log pipeline catches it.
//! - **5-minute TTL.** Pending registration / assertion challenges expire
//!   after 5 minutes via `WHERE created_at > now() - INTERVAL '5 minutes'` on
//!   lookup; the row is deleted at the same time so a successful
//!   register/assert is single-use.
//!
//! # State serialisation
//!
//! `webauthn-rs` 0.5 only derives `Serialize`/`Deserialize` for
//! [`PasskeyRegistration`] / [`PasskeyAuthentication`] when the
//! `danger-allow-state-serialisation` feature is enabled. We pay that price
//! deliberately: persisting the framework's opaque state object is the
//! correct alternative to either (a) shipping it in a cookie (forbidden by
//! design.md §6) or (b) re-implementing CSRF/replay protection by hand
//! around a hand-rolled challenge column.
//!
//! [`PasskeyRegistration`]: webauthn_rs::prelude::PasskeyRegistration
//! [`PasskeyAuthentication`]: webauthn_rs::prelude::PasskeyAuthentication

use std::sync::Arc;

use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use rand::RngCore;
use rand::rngs::OsRng;
use sqlx::PgPool;
use url::Url;
use webauthn_rs::Webauthn;
use webauthn_rs::prelude::{
    CreationChallengeResponse, Passkey, PasskeyAuthentication, PasskeyRegistration,
    PublicKeyCredential, RegisterPublicKeyCredential, RequestChallengeResponse, WebauthnBuilder,
};

use crate::auth::ModeratorId;

/// Length in bytes of the opaque `state` token issued by
/// [`WebauthnVerifier::register_start`] / [`WebauthnVerifier::assert_start`].
///
/// 32 bytes = 256 bits, the same entropy budget the session-cookie token uses
/// (see [`crate::auth::session::SESSION_ID_BYTES`]).
pub const STATE_TOKEN_BYTES: usize = 32;

/// TTL for pending registration / assertion challenges, in minutes.
///
/// Matches the design-document discipline ("Challenge state held in [the DB]
/// with short TTL (5 min); never in cookies"). The lookup queries enforce it
/// via `WHERE created_at > now() - INTERVAL '5 minutes'`; this constant is
/// the canonical source so the SQL literal can be regenerated by a future
/// query builder without drift.
pub const CHALLENGE_TTL_MINUTES: i64 = 5;

/// Errors raised by [`WebauthnVerifier`] and surfaced through the HTTP layer
/// in [`crate::api::webauthn`].
///
/// `Display` text is deliberately generic for the cases that surface to
/// untrusted callers — the framework error is captured via `#[source]` for
/// structured logs but is never echoed back over HTTP. The
/// [`Self::CloningDetected`] variant intentionally exposes the counter values
/// in `Display` so the security operator running the log pipeline gets the
/// numbers without paying for a debug-format chain.
#[derive(Debug, thiserror::Error)]
pub enum WebauthnError {
    /// `state` did not match a row in `webauthn_register_states`, or the row
    /// was older than [`CHALLENGE_TTL_MINUTES`] minutes. Either expiry or
    /// forgery; the verifier does not distinguish so a probe cannot tell
    /// them apart.
    #[error("registration challenge expired or unknown")]
    UnknownRegisterState,

    /// `state` did not match a row in `webauthn_assert_states`, or the row
    /// was older than [`CHALLENGE_TTL_MINUTES`] minutes. Same rationale as
    /// [`Self::UnknownRegisterState`].
    #[error("assertion challenge expired or unknown")]
    UnknownAssertState,

    /// The `webauthn-rs` framework rejected the registration ceremony
    /// (attestation invalid, challenge mismatch, ...).
    #[error("webauthn registration failed")]
    RegisterFailed(
        /// Underlying framework error.
        #[source]
        webauthn_rs::prelude::WebauthnError,
    ),

    /// The `webauthn-rs` framework rejected the assertion ceremony
    /// (signature invalid, origin mismatch, ...).
    #[error("webauthn assertion failed")]
    AssertFailed(
        /// Underlying framework error.
        #[source]
        webauthn_rs::prelude::WebauthnError,
    ),

    /// `sign_count` regression detected: the authenticator presented a
    /// counter that is not strictly greater than the stored counter. Per
    /// WebAuthn L3 §7.2 step 21, this is a strong cloning red-flag. The
    /// numbers are surfaced in `Display` so the security operator's log
    /// query can correlate against the credential's history.
    #[error("clone detected: sign_count regressed (stored={stored}, presented={presented})")]
    CloningDetected {
        /// Counter recorded in `webauthn_credentials.sign_count` at the time
        /// of this assertion.
        stored: i64,
        /// Counter the authenticator just presented.
        presented: i64,
    },

    /// Configuration-layer rejection of the `rp_id` / `rp_origin` pair (the
    /// origin's effective domain is not the `rp_id`).
    #[error("invalid webauthn relying-party configuration")]
    Config(
        /// Underlying framework error from [`WebauthnBuilder::build`].
        #[source]
        webauthn_rs::prelude::WebauthnError,
    ),

    /// Database failure during a `webauthn_*` table operation.
    #[error("db error during webauthn ceremony")]
    Db(
        /// Underlying sqlx error.
        #[source]
        sqlx::Error,
    ),

    /// Failed to encode or decode the framework's `PasskeyRegistration` /
    /// `PasskeyAuthentication` / `Passkey` state blob.
    #[error("webauthn state codec failure: {message}")]
    Codec {
        /// Operator-facing description of which conversion failed.
        message: String,
    },
}

impl From<sqlx::Error> for WebauthnError {
    fn from(value: sqlx::Error) -> Self {
        Self::Db(value)
    }
}

/// Result of [`WebauthnVerifier::register_start`].
///
/// `challenge` is the `CreationChallengeResponse` the browser's
/// `navigator.credentials.create({ publicKey: ... })` consumes; `state` is
/// the opaque token the caller must echo back to [`WebauthnVerifier::register_finish`].
#[derive(Debug)]
pub struct RegisterStartResponse {
    /// Server-authored challenge to forward to the browser as the
    /// `publicKey` field of `CredentialCreationOptions`.
    pub challenge: CreationChallengeResponse,
    /// Opaque correlator the client returns to [`WebauthnVerifier::register_finish`].
    pub state: String,
}

/// Result of [`WebauthnVerifier::assert_start`].
#[derive(Debug)]
pub struct AssertStartResponse {
    /// Server-authored challenge to forward to the browser as the
    /// `publicKey` field of `CredentialRequestOptions`.
    pub challenge: RequestChallengeResponse,
    /// Opaque correlator the client returns to [`WebauthnVerifier::assert_finish`].
    pub state: String,
}

/// Hardware-key (WebAuthn / FIDO2) verifier.
///
/// Holds an `Arc<webauthn_rs::Webauthn>` plus a `sqlx::PgPool`. The framework
/// state is shared across requests; the pool clones cheaply (internally
/// `Arc`-backed).
#[derive(Debug, Clone)]
pub struct WebauthnVerifier {
    inner: Arc<Webauthn>,
    pool: PgPool,
}

impl WebauthnVerifier {
    /// Build a verifier against the relying party (`rp_id`) and origin
    /// (`rp_origin`).
    ///
    /// `rp_id` MUST be an effective domain of `rp_origin` (the underlying
    /// framework rejects mismatches at build time).
    ///
    /// # Errors
    ///
    /// Returns [`WebauthnError::Config`] when the `rp_id` / `rp_origin`
    /// pair fails the `webauthn-rs` validity check.
    pub fn new(rp_id: &str, rp_origin: &Url, pool: PgPool) -> Result<Self, WebauthnError> {
        let builder = WebauthnBuilder::new(rp_id, rp_origin).map_err(WebauthnError::Config)?;
        let inner = builder.build().map_err(WebauthnError::Config)?;
        Ok(Self {
            inner: Arc::new(inner),
            pool,
        })
    }

    /// Begin a registration ceremony for an already-authenticated moderator.
    ///
    /// The caller MUST have completed OIDC / ATProto authentication first —
    /// the gate (see [`crate::auth::login_gate`]) decides when to call this.
    ///
    /// # Errors
    ///
    /// - [`WebauthnError::RegisterFailed`] when the framework refuses to
    ///   generate a challenge.
    /// - [`WebauthnError::Codec`] when the framework's `PasskeyRegistration`
    ///   cannot be bincode-encoded (a defensive guard against future shape
    ///   churn).
    /// - [`WebauthnError::Db`] on insert failure.
    pub async fn register_start(
        &self,
        moderator_id: ModeratorId,
    ) -> Result<RegisterStartResponse, WebauthnError> {
        // Load any existing credentials so the framework can exclude them
        // (prevents duplicate-credential registrations on the same key).
        let exclude_ids = self.load_credential_ids(moderator_id).await?;

        let (challenge, registration) = self
            .inner
            .start_passkey_registration(
                *moderator_id.as_uuid(),
                // user_name / user_display_name: the WebAuthn spec uses
                // these for browser UI only — they are NOT a trust anchor.
                // We render the moderator's UUID so the disambiguation in
                // the browser key-picker is stable across renames.
                &moderator_id.to_string(),
                &moderator_id.to_string(),
                exclude_ids,
            )
            .map_err(WebauthnError::RegisterFailed)?;

        let state = generate_state_token();
        let blob = encode_state(&registration)?;

        sqlx::query!(
            r"INSERT INTO webauthn_register_states (state, moderator_id, challenge_state)
              VALUES ($1, $2, $3)",
            state,
            moderator_id.0,
            &blob,
        )
        .execute(&self.pool)
        .await?;

        Ok(RegisterStartResponse { challenge, state })
    }

    /// Complete the registration ceremony started by
    /// [`Self::register_start`].
    ///
    /// On success the credential row is persisted to `webauthn_credentials`.
    /// The state row is deleted atomically with the lookup so replay is
    /// impossible even on a downstream INSERT failure.
    ///
    /// # Errors
    ///
    /// - [`WebauthnError::UnknownRegisterState`] when the state token does
    ///   not match a non-expired row.
    /// - [`WebauthnError::RegisterFailed`] when the framework rejects the
    ///   client-side response (attestation invalid, challenge mismatch).
    /// - [`WebauthnError::Codec`] on bincode encode/decode failure.
    /// - [`WebauthnError::Db`] on row-level errors.
    pub async fn register_finish(
        &self,
        state: &str,
        response: &RegisterPublicKeyCredential,
    ) -> Result<ModeratorId, WebauthnError> {
        let mut tx = self.pool.begin().await?;

        let row = sqlx::query!(
            r"SELECT moderator_id, challenge_state
              FROM webauthn_register_states
              WHERE state = $1
                AND created_at > now() - INTERVAL '5 minutes'",
            state,
        )
        .fetch_optional(&mut *tx)
        .await?
        .ok_or(WebauthnError::UnknownRegisterState)?;

        // Single-use: delete before applying the framework validation so a
        // failed finish still consumes the challenge.
        sqlx::query!(
            r"DELETE FROM webauthn_register_states WHERE state = $1",
            state,
        )
        .execute(&mut *tx)
        .await?;

        let registration: PasskeyRegistration = decode_state(&row.challenge_state)?;

        let passkey = self
            .inner
            .finish_passkey_registration(response, &registration)
            .map_err(WebauthnError::RegisterFailed)?;

        let credential_id: Vec<u8> = passkey.cred_id().as_ref().to_vec();
        let public_key_blob = encode_state(&passkey)?;
        let moderator_id = ModeratorId(row.moderator_id);

        sqlx::query!(
            r"INSERT INTO webauthn_credentials
                (moderator_id, credential_id, public_key, sign_count)
              VALUES ($1, $2, $3, 0)",
            moderator_id.0,
            credential_id,
            public_key_blob,
        )
        .execute(&mut *tx)
        .await?;

        tx.commit().await?;
        Ok(moderator_id)
    }

    /// Begin an assertion ceremony for a moderator with at least one
    /// registered credential.
    ///
    /// # Errors
    ///
    /// - [`WebauthnError::AssertFailed`] when the framework cannot build a
    ///   challenge (e.g. the credential set is empty after a race deleted
    ///   the row).
    /// - [`WebauthnError::Codec`] on bincode encode failure.
    /// - [`WebauthnError::Db`] on lookup / insert failure.
    pub async fn assert_start(
        &self,
        moderator_id: ModeratorId,
    ) -> Result<AssertStartResponse, WebauthnError> {
        let credentials = self.load_credentials(moderator_id).await?;

        let (challenge, authentication) = self
            .inner
            .start_passkey_authentication(&credentials)
            .map_err(WebauthnError::AssertFailed)?;

        let state = generate_state_token();
        let blob = encode_state(&authentication)?;

        sqlx::query!(
            r"INSERT INTO webauthn_assert_states (state, moderator_id, challenge_state)
              VALUES ($1, $2, $3)",
            state,
            moderator_id.0,
            &blob,
        )
        .execute(&self.pool)
        .await?;

        Ok(AssertStartResponse { challenge, state })
    }

    /// Complete the assertion ceremony started by [`Self::assert_start`].
    ///
    /// Performs the WebAuthn L3 §7.2 step-21 monotonic counter check before
    /// updating the stored counter. A regression raises
    /// [`WebauthnError::CloningDetected`] and emits `tracing::error!`.
    ///
    /// # Errors
    ///
    /// - [`WebauthnError::UnknownAssertState`] when the state token does
    ///   not match a non-expired row.
    /// - [`WebauthnError::AssertFailed`] on framework-level signature /
    ///   origin / challenge failure.
    /// - [`WebauthnError::CloningDetected`] on a counter regression — this
    ///   is the primary cloning red-flag.
    /// - [`WebauthnError::Codec`] on bincode decode failure.
    /// - [`WebauthnError::Db`] on row-level errors.
    pub async fn assert_finish(
        &self,
        state: &str,
        response: &PublicKeyCredential,
    ) -> Result<ModeratorId, WebauthnError> {
        let mut tx = self.pool.begin().await?;

        let row = sqlx::query!(
            r"SELECT moderator_id, challenge_state
              FROM webauthn_assert_states
              WHERE state = $1
                AND created_at > now() - INTERVAL '5 minutes'",
            state,
        )
        .fetch_optional(&mut *tx)
        .await?
        .ok_or(WebauthnError::UnknownAssertState)?;

        sqlx::query!(
            r"DELETE FROM webauthn_assert_states WHERE state = $1",
            state,
        )
        .execute(&mut *tx)
        .await?;

        let authentication: PasskeyAuthentication = decode_state(&row.challenge_state)?;

        let result = self
            .inner
            .finish_passkey_authentication(response, &authentication)
            .map_err(WebauthnError::AssertFailed)?;

        let credential_id_bytes: &[u8] = result.cred_id().as_ref();
        let presented_counter = i64::from(result.counter());

        // Monotonic counter check (WebAuthn L3 §7.2 step 21). The framework
        // already verifies the signature, but the counter rule belongs to
        // the relying party. A presented counter that is NOT strictly
        // greater than the stored one is a clone red-flag.
        let stored_row = sqlx::query!(
            r"SELECT sign_count FROM webauthn_credentials
              WHERE credential_id = $1
              FOR UPDATE",
            credential_id_bytes,
        )
        .fetch_one(&mut *tx)
        .await?;

        // Counters in WebAuthn are u32 but always non-negative. The
        // `webauthn_credentials.sign_count` column is BIGINT to leave
        // headroom; the cast is lossless.
        let stored_counter: i64 = stored_row.sign_count;

        // Note the strict inequality: a counter that is *equal* to the
        // stored one is itself a red-flag, because a non-zero
        // counter MUST strictly increase between authentications per the
        // spec. Authenticators that don't support counters return 0 every
        // time — the framework records the initial 0 and a continuing 0
        // here is allowed via the `stored == 0 && presented == 0` short-
        // circuit below.
        let counters_pinned_at_zero = stored_counter == 0 && presented_counter == 0;
        if !counters_pinned_at_zero && presented_counter <= stored_counter {
            tracing::error!(
                target: "polaris::auth::webauthn",
                stored = stored_counter,
                presented = presented_counter,
                "webauthn clone detected: sign_count regression"
            );
            // Drop the transaction without commit; the state row is already
            // gone (single-use) so the attacker cannot retry.
            return Err(WebauthnError::CloningDetected {
                stored: stored_counter,
                presented: presented_counter,
            });
        }

        sqlx::query!(
            r"UPDATE webauthn_credentials
              SET sign_count = $1,
                  last_used_at = now()
              WHERE credential_id = $2",
            presented_counter,
            credential_id_bytes,
        )
        .execute(&mut *tx)
        .await?;

        tx.commit().await?;

        Ok(ModeratorId(row.moderator_id))
    }

    /// Return `true` if `moderator_id` has at least one row in
    /// `webauthn_credentials`.
    ///
    /// # Errors
    ///
    /// - [`WebauthnError::Db`] on query failure.
    pub async fn has_credentials(&self, moderator_id: ModeratorId) -> Result<bool, WebauthnError> {
        let exists = sqlx::query_scalar!(
            r#"SELECT EXISTS (
                  SELECT 1 FROM webauthn_credentials WHERE moderator_id = $1
              ) AS "exists!""#,
            moderator_id.0,
        )
        .fetch_one(&self.pool)
        .await?;
        Ok(exists)
    }

    /// Internal: load every `Passkey` for the moderator (used by
    /// `assert_start`).
    async fn load_credentials(
        &self,
        moderator_id: ModeratorId,
    ) -> Result<Vec<Passkey>, WebauthnError> {
        let rows = sqlx::query!(
            r"SELECT public_key FROM webauthn_credentials WHERE moderator_id = $1",
            moderator_id.0,
        )
        .fetch_all(&self.pool)
        .await?;

        let mut out = Vec::with_capacity(rows.len());
        for row in rows {
            let key: Passkey = decode_state(&row.public_key)?;
            out.push(key);
        }
        Ok(out)
    }

    /// Internal: load credential IDs for the moderator (used by
    /// `register_start` to exclude already-registered authenticators).
    async fn load_credential_ids(
        &self,
        moderator_id: ModeratorId,
    ) -> Result<Option<Vec<webauthn_rs::prelude::CredentialID>>, WebauthnError> {
        let rows = sqlx::query!(
            r"SELECT credential_id FROM webauthn_credentials WHERE moderator_id = $1",
            moderator_id.0,
        )
        .fetch_all(&self.pool)
        .await?;
        if rows.is_empty() {
            return Ok(None);
        }
        let ids = rows
            .into_iter()
            .map(|r| webauthn_rs::prelude::CredentialID::from(r.credential_id))
            .collect();
        Ok(Some(ids))
    }
}

/// Generate a fresh URL-safe state token. 32 bytes of `OsRng` entropy,
/// base64url-encoded (no padding). The wire form is 43 ASCII characters.
fn generate_state_token() -> String {
    let mut buf = [0_u8; STATE_TOKEN_BYTES];
    OsRng.fill_bytes(&mut buf);
    URL_SAFE_NO_PAD.encode(buf)
}

/// Bincode-encode any `Serialize` state object (used uniformly for
/// `PasskeyRegistration`, `PasskeyAuthentication`, and `Passkey` itself).
///
/// Bincode is the same envelope the bus layer uses (#16); it's compact and
/// keeps the framework type's invariants intact. JSON would also work but
/// would inflate the row size 2-3x for no benefit (the column is internal,
/// never user-rendered).
fn encode_state<T: serde::Serialize>(value: &T) -> Result<Vec<u8>, WebauthnError> {
    bincode::serde::encode_to_vec(value, bincode::config::standard()).map_err(|e| {
        WebauthnError::Codec {
            message: format!("encode: {e}"),
        }
    })
}

/// Inverse of [`encode_state`].
fn decode_state<T>(bytes: &[u8]) -> Result<T, WebauthnError>
where
    T: for<'de> serde::Deserialize<'de>,
{
    let (value, _) = bincode::serde::decode_from_slice(bytes, bincode::config::standard())
        .map_err(|e| WebauthnError::Codec {
            message: format!("decode: {e}"),
        })?;
    Ok(value)
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "test code is allowed to panic — rust-quality §7 convention"
)]
mod tests {
    use super::*;

    #[test]
    fn state_token_is_base64url_43_chars() {
        let t = generate_state_token();
        assert_eq!(t.len(), 43);
        for c in t.chars() {
            assert!(
                c.is_ascii_alphanumeric() || c == '-' || c == '_',
                "non-base64url char: {c}"
            );
        }
    }

    #[test]
    fn two_state_tokens_differ() {
        let a = generate_state_token();
        let b = generate_state_token();
        assert_ne!(a, b, "state tokens must be distinct");
    }

    #[test]
    fn webauthn_error_display_is_informative() {
        // Stored / presented appear verbatim in the Display string so the
        // log-aggregation pipeline can parse them without unwinding the
        // Debug chain.
        let err = WebauthnError::CloningDetected {
            stored: 7,
            presented: 3,
        };
        let msg = err.to_string();
        assert!(msg.contains("stored=7"), "missing stored counter: {msg}");
        assert!(
            msg.contains("presented=3"),
            "missing presented counter: {msg}"
        );

        let err = WebauthnError::UnknownRegisterState;
        assert!(
            err.to_string().contains("registration challenge"),
            "unexpected Display: {err}"
        );

        let err = WebauthnError::UnknownAssertState;
        assert!(
            err.to_string().contains("assertion challenge"),
            "unexpected Display: {err}"
        );
    }

    #[test]
    fn challenge_ttl_constant_is_five_minutes() {
        // The SQL literal is duplicated in the lookup queries; this assertion
        // catches an accidental edit that would desync the two sites.
        assert_eq!(CHALLENGE_TTL_MINUTES, 5);
    }

    #[test]
    fn state_token_bytes_constant_matches_session_token() {
        // The state token shares the entropy budget with the session token
        // (see `crate::auth::session::SESSION_ID_BYTES`). Locking it down so
        // a future drift surfaces as a deliberate edit.
        assert_eq!(STATE_TOKEN_BYTES, 32);
    }
}
