-- Auth: moderators, moderator roles, sessions with encrypted refresh tokens.
-- Per design.md §6: SSO with Polaris-issued opaque session cookies. The
-- moderator table is `auth_backend`-agnostic so M4 can plug ATProto OAuth
-- alongside OIDC without a schema change.

-- pgcrypto is part of PostgreSQL's contrib modules and ships with every
-- supported PostgreSQL release. `gen_random_uuid()` is a built-in on
-- PostgreSQL 13+, but enabling pgcrypto here keeps the migration portable
-- to older PG fixtures (the default testcontainers-modules Postgres tag is
-- PG 11) and to vendored deployments that haven't yet upgraded the server.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE moderators (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- external_id is the `sub` claim for OIDC, the moderator's DID for the
    -- ATProto OAuth backend that lands in #31.
    external_id TEXT NOT NULL,
    auth_backend TEXT NOT NULL CHECK (auth_backend IN ('oidc', 'atproto')),
    display_name TEXT,
    csam_trained BOOLEAN NOT NULL DEFAULT FALSE,
    calibration_complete BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    UNIQUE (auth_backend, external_id)
);

CREATE TABLE moderator_roles (
    moderator_id UUID NOT NULL REFERENCES moderators(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('admin','senior_moderator','moderator','triage','read_only')),
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    granted_by UUID REFERENCES moderators(id),
    PRIMARY KEY (moderator_id, role)
);

CREATE TABLE sessions (
    -- Session ID is opaque, generated by Polaris from `OsRng`.
    -- 32 random bytes base64url-encoded (no padding) — 43 chars.
    id TEXT PRIMARY KEY,
    moderator_id UUID NOT NULL REFERENCES moderators(id) ON DELETE CASCADE,
    -- refresh_token_enc is the CBOR-free, length-prefixed [nonce(12) || ciphertext]
    -- encoding of `SealedBytes` documented in `auth/crypto.rs`. AES-256-GCM
    -- authenticates the ciphertext; tampering surfaces as a decrypt error.
    refresh_token_enc BYTEA NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX sessions_moderator_id_idx ON sessions(moderator_id);
CREATE INDEX sessions_expires_at_idx ON sessions(expires_at);

-- OIDC login-state holding table: stores the PKCE verifier + CSRF nonce
-- between the `/auth/oidc/login` redirect and the `/auth/oidc/callback`
-- code exchange. Rows are scoped to the random `state` parameter the
-- authorization server echoes back. Entries expire 10 minutes after creation;
-- a sweeper or `WHERE created_at > now() - interval '10 minutes'` filter
-- enforces the TTL.
CREATE TABLE auth_oidc_login_states (
    state TEXT PRIMARY KEY,
    pkce_verifier TEXT NOT NULL,
    csrf_nonce TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX auth_oidc_login_states_created_at_idx ON auth_oidc_login_states(created_at);

-- Schema-version marker (mirrors the pattern in 00000000000000_init.sql).
INSERT INTO _polaris_schema_version (version, description) VALUES (2, 'auth');
